// Generates docs/reference/deployments.md, docs/reference/launch-configuration.md,
// docs/reference/contracts/README.md, and docs/reference/contracts/*.md from the
// JSON files in data/. Node built-ins only, no dependencies. Deterministic: same
// input produces byte-identical output.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dataDir = path.join(root, "data");
const outDir = process.argv[2] ? path.resolve(process.argv[2]) : path.join(root, "docs", "reference");

const MARKER = "<!-- generated by scripts/render.mjs from data/ ; do not edit -->";

const SLUGS = {
  MidwayBuyer: "midway-buyer",
  MidwayRegistry: "midway-registry",
  FwaEngineV1: "fwa-engine-v1",
  RequestBuyer: "request-buyer",
  AssetPolicy: "asset-policy",
  RewardVault: "reward-vault",
  RewardSplitter: "reward-splitter",
  SharedUpside: "shared-upside",
  ReferralRewards: "referral-rewards",
  FwaConversionFloor: "fwa-conversion-floor",
  ChainlinkVrfAdapter: "chainlink-vrf-adapter",
  MidwayBatchAccountFactory: "midway-batch-account-factory",
  MidwayBatchAccount: "midway-batch-account",
};

function readJson(name) {
  return JSON.parse(readFileSync(path.join(dataDir, name), "utf8"));
}

const mainnet = readJson("mainnet.json");
const sepolia = readJson("sepolia.json");
const config = readJson("config.json");
const reference = readJson("reference.json");

// ---------- text helpers ----------

const EM_DASH = "—";
const EN_DASH = "–";

function noDash(s) {
  if (typeof s !== "string") return s;
  return s.split(EM_DASH).join(",").split(EN_DASH).join(",");
}

function cell(s) {
  if (s === undefined || s === null) return "";
  return noDash(String(s)).split("|").join("\\|");
}

function code(s) {
  return "`" + s + "`";
}

function addressUrl(address, chainId) {
  return `https://evm.now/address/${address}?chainId=${chainId}`;
}

function addressLink(address, chainId) {
  return `[${code(address)}](${addressUrl(address, chainId)})`;
}

function truncateHash(hash, len = 10) {
  if (!hash) return null;
  return hash.slice(0, len) + "...";
}

function table(headers, rows) {
  const out = [];
  out.push("| " + headers.join(" | ") + " |");
  out.push("| " + headers.map(() => "---").join(" | ") + " |");
  for (const row of rows) out.push("| " + row.join(" | ") + " |");
  return out.join("\n");
}

// ---------- config value formatting ----------

function weiToEth(weiStr) {
  const wei = BigInt(weiStr);
  const negative = wei < 0n;
  const abs = negative ? -wei : wei;
  const whole = abs / 1000000000000000000n;
  let frac = (abs % 1000000000000000000n).toString().padStart(18, "0");
  frac = frac.replace(/0+$/, "");
  const s = frac.length ? `${whole}.${frac}` : `${whole}`;
  return (negative ? "-" : "") + s;
}

function unixToUtc(ts) {
  return new Date(ts * 1000).toISOString().replace(".000Z", "Z");
}

function secondsToHuman(seconds) {
  if (seconds !== 0 && seconds % 86400 === 0) {
    const days = seconds / 86400;
    return `${days} day${days === 1 ? "" : "s"}`;
  }
  if (seconds !== 0 && seconds % 3600 === 0) {
    const hours = seconds / 3600;
    return `${hours} hour${hours === 1 ? "" : "s"}`;
  }
  return null;
}

function bpsToPercent(bps) {
  const pct = bps / 100;
  return `${pct % 1 === 0 ? pct.toFixed(0) : pct.toFixed(2)}%`;
}

function formatConfigValue(entry) {
  const { value, unit } = entry;
  switch (unit) {
    case "wei": {
      const raw = code(String(value));
      return `${raw} (${weiToEth(String(value))} ETH)`;
    }
    case "unix timestamp": {
      return `${code(String(value))} (${unixToUtc(value)})`;
    }
    case "seconds": {
      const human = secondsToHuman(value);
      return human ? `${code(String(value))} (${human})` : code(String(value));
    }
    case "bps": {
      return `${code(String(value))} (${bpsToPercent(value)})`;
    }
    case "id": {
      return code(String(value));
    }
    case "bool": {
      return code(String(value));
    }
    default:
      return code(String(value));
  }
}

// ---------- deployments.md ----------

function renderDeployedContractsTable(contracts, chainId) {
  const rows = contracts.map((c) => [
    cell(c.name),
    addressLink(c.address, chainId),
    c.codeHash ? code(truncateHash(c.codeHash)) : "not recorded",
  ]);
  const lines = [table(["Contract", "Address", "Runtime code hash"], rows)];

  const withHash = contracts.filter((c) => c.codeHash);
  if (withHash.length) {
    lines.push("");
    lines.push("<details>");
    lines.push("<summary>Full runtime code hashes</summary>");
    lines.push("");
    lines.push(table(["Contract", "Runtime code hash"], withHash.map((c) => [cell(c.name), code(c.codeHash)])));
    lines.push("");
    lines.push("</details>");
  }
  return lines.join("\n");
}

function renderMainnetSection() {
  const lines = [];
  lines.push("## Mainnet");
  lines.push("");
  lines.push(`- **Release**: ${code(mainnet.releaseId)}`);
  lines.push(`- **Deploy block**: ${mainnet.deployBlock}`);
  lines.push(`- **Source**: ${code(mainnet.tag)} (${code(mainnet.commit)})`);
  if (mainnet.deployer) {
    lines.push(`- **Deployer**: ${addressLink(mainnet.deployer, mainnet.chainId)}`);
  }
  if (mainnet.owner) {
    lines.push(`- **Owner**: ${addressLink(mainnet.owner, mainnet.chainId)}`);
  }
  if (mainnet.status === "paused") {
    lines.push(`- **Status**: Paused. Activation pending.`);
  }
  lines.push("");
  lines.push("### Contracts");
  lines.push("");
  lines.push(renderDeployedContractsTable(mainnet.contracts, mainnet.chainId));

  const external = mainnet.external || [];
  if (external.length) {
    lines.push("");
    lines.push("### External contracts");
    lines.push("");
    lines.push(
      table(
        ["Name", "Address"],
        external.map((e) => [cell(e.name), addressLink(e.address, mainnet.chainId)])
      )
    );
  }

  const restricted = external.filter((e) => e.restricted);
  if (restricted.length) {
    lines.push("");
    lines.push("### ETH only collections");
    lines.push("");
    lines.push(
      "Manual NFT delivery is denied for these collections. Managed ETH and $FWA settlement are unaffected."
    );
    lines.push("");
    lines.push(
      table(
        ["Name", "Address"],
        restricted.map((e) => [cell(e.name), addressLink(e.address, mainnet.chainId)])
      )
    );
  }

  return lines.join("\n");
}

function renderSepoliaSection() {
  const lines = [];
  lines.push("## Sepolia");
  lines.push("");
  lines.push("{% hint style=\"warning\" %}");
  lines.push("Testnet addresses. Never use a Sepolia address on mainnet.");
  lines.push("{% endhint %}");
  lines.push("");
  lines.push(`- **Release**: ${code(sepolia.releaseId)}`);
  lines.push(`- **Deploy block**: ${sepolia.deployBlock}`);
  lines.push(`- **Source**: ${code(sepolia.tag)} (${code(sepolia.commit)})`);
  if (sepolia.status === "paused") {
    lines.push(`- **Status**: Paused. Activation pending.`);
  }
  if (sepolia.note) {
    lines.push(`- **Note**: ${cell(sepolia.note)}`);
  }
  lines.push("");
  lines.push("### Contracts");
  lines.push("");
  lines.push(renderDeployedContractsTable(sepolia.contracts, sepolia.chainId));

  const external = sepolia.external || [];
  if (external.length) {
    lines.push("");
    lines.push("### External contracts");
    lines.push("");
    lines.push(
      table(
        ["Name", "Address"],
        external.map((e) => [cell(e.name), addressLink(e.address, sepolia.chainId)])
      )
    );
  }
  const restricted = external.filter((e) => e.restricted);
  if (restricted.length) {
    lines.push("");
    lines.push("### ETH only collections");
    lines.push("");
    lines.push(
      "Manual NFT delivery is denied for these collections. Managed ETH and $FWA settlement are unaffected."
    );
    lines.push("");
    lines.push(
      table(
        ["Name", "Address"],
        restricted.map((e) => [cell(e.name), addressLink(e.address, sepolia.chainId)])
      )
    );
  }

  return lines.join("\n");
}

function renderDeploymentsPage() {
  const lines = [];
  lines.push("# Deployments");
  lines.push("");
  lines.push(MARKER);
  lines.push("");
  lines.push(renderMainnetSection());
  lines.push("");
  lines.push(renderSepoliaSection());
  lines.push("");
  return lines.join("\n");
}

// ---------- launch-configuration.md ----------

function renderLaunchConfigPage() {
  const lines = [];
  lines.push("# Launch configuration");
  lines.push("");
  lines.push(MARKER);
  lines.push("");
  lines.push(
    table(
      ["Key", "Value", "Unit", "Description"],
      config.entries.map((e) => [code(e.key), formatConfigValue(e), cell(e.unit), cell(e.description)])
    )
  );
  lines.push("");
  return lines.join("\n");
}

// ---------- contracts/README.md ----------

function findMainnetEntry(name) {
  return mainnet.contracts.find((c) => c.name === name);
}

function renderContractsIndexPage() {
  const lines = [];
  lines.push("# Contracts");
  lines.push("");
  lines.push(MARKER);
  lines.push("");
  const rows = reference.contracts.map((c) => {
    const slug = SLUGS[c.name];
    const entry = findMainnetEntry(c.name);
    const addressCell = entry ? addressLink(entry.address, mainnet.chainId) : "Deployed per application";
    return [
      `[${cell(c.name)}](${slug}.md)`,
      code(c.source),
      addressCell,
      String(c.functions.length),
      String(c.events.length),
      String(c.errors.length),
    ];
  });
  lines.push(table(["Contract", "Source", "Address", "Functions", "Events", "Errors"], rows));
  lines.push("");
  return lines.join("\n");
}

// ---------- contracts/<slug>.md ----------

function renderFunctionDetails(fn) {
  const hasDev = fn.dev && fn.dev.length > 0;
  const hasParams = fn.params && Object.keys(fn.params).length > 0;
  if (!hasDev && !hasParams) return null;

  const lines = [];
  lines.push("<details>");
  lines.push(`<summary>${code(fn.signature)}</summary>`);
  lines.push("");
  if (hasDev) {
    lines.push(noDash(fn.dev));
    lines.push("");
  }
  if (hasParams) {
    lines.push("Parameters:");
    lines.push("");
    for (const input of fn.inputs) {
      if (!(input.name in fn.params)) continue;
      lines.push(`- ${code(input.name)} (${code(input.type)}): ${noDash(fn.params[input.name])}`);
    }
    lines.push("");
  }
  lines.push("</details>");
  return lines.join("\n");
}

function renderFunctionGroup(title, fns) {
  if (!fns.length) return [];
  const lines = [];
  lines.push(`### ${title}`);
  lines.push("");
  lines.push(table(["Function", "Notice"], fns.map((f) => [code(f.signature), cell(f.notice)])));

  const details = fns.map(renderFunctionDetails).filter(Boolean);
  if (details.length) {
    lines.push("");
    lines.push(details.join("\n\n"));
  }
  return lines;
}

function renderEventsSection(events) {
  if (!events.length) return [];
  const lines = [];
  lines.push("## Events");
  lines.push("");
  const rows = events.map((e) => {
    const topicCell = e.topic0
      ? `${code(e.signature)}<br><details><summary>${code(truncateHash(e.topic0))}</summary>${code(
          e.topic0
        )}</details>`
      : code(e.signature);
    return [topicCell, cell(e.notice)];
  });
  lines.push(table(["Event", "Notice"], rows));
  return lines;
}

function renderErrorsSection(errors) {
  if (!errors.length) return [];
  const lines = [];
  lines.push("## Errors");
  lines.push("");
  lines.push(
    table(
      ["Error", "Selector", "Notice"],
      errors.map((e) => [code(e.signature), code(e.selector), cell(e.notice)])
    )
  );
  return lines;
}

function renderContractPage(c) {
  const lines = [];
  lines.push(`# ${c.name}`);
  lines.push("");
  lines.push(MARKER);
  lines.push("");

  if (c.notice) {
    lines.push(noDash(c.notice));
    lines.push("");
  }

  if (c.name === "MidwayBatchAccount") {
    lines.push("**Address**: deployed per application as a clone of the implementation.");
  } else {
    const entry = findMainnetEntry(c.name);
    if (entry) {
      lines.push(`**Address**: ${addressLink(entry.address, mainnet.chainId)}`);
      if (c.name === "RequestBuyer") {
        lines.push("");
        lines.push("The listed address is the implementation cloned per request.");
      }
    }
  }
  lines.push(`**Source**: ${code(c.source)}`);
  lines.push("");

  lines.push("## Functions");
  lines.push("");
  const stateChanging = c.functions.filter((f) => f.stateMutability === "nonpayable" || f.stateMutability === "payable");
  const viewFns = c.functions.filter((f) => f.stateMutability === "view" || f.stateMutability === "pure");
  const fnLines = [
    ...renderFunctionGroup("State changing", stateChanging),
    ...(stateChanging.length && viewFns.length ? [""] : []),
    ...renderFunctionGroup("View", viewFns),
  ];
  lines.push(...fnLines);
  lines.push("");

  const eventLines = renderEventsSection(c.events);
  if (eventLines.length) {
    lines.push(...eventLines);
    lines.push("");
  }

  const errorLines = renderErrorsSection(c.errors);
  if (errorLines.length) {
    lines.push(...errorLines);
    lines.push("");
  }

  return lines.join("\n");
}

// ---------- write ----------

function writePage(relPath, content) {
  const full = path.join(outDir, relPath);
  mkdirSync(path.dirname(full), { recursive: true });
  // single trailing newline, no trailing whitespace on lines
  const normalized = content
    .split("\n")
    .map((l) => l.replace(/[ \t]+$/, ""))
    .join("\n")
    .replace(/\n+$/, "") + "\n";
  writeFileSync(full, normalized);
}

writePage("deployments.md", renderDeploymentsPage());
writePage("launch-configuration.md", renderLaunchConfigPage());
writePage(path.join("contracts", "README.md"), renderContractsIndexPage());
for (const c of reference.contracts) {
  const slug = SLUGS[c.name];
  if (!slug) throw new Error(`no slug mapping for contract ${c.name}`);
  writePage(path.join("contracts", `${slug}.md`), renderContractPage(c));
}

console.log(`rendered ${2 + 1 + reference.contracts.length} page(s) into ${path.relative(root, outDir)}`);
